### PR TITLE
dont need 32bit motif, need 64: motif and xt, #280

### LINKED ISSUE #280: circleci
circleci build is failing.
Apparently, the circleci environment does not have 64-bit versions of motif and Xt. When I converted pulsetool to use 64-bit motif, the circleci build breaks.

### PR DESCRIPTION
**Pull request by tesch1**
This fixes #280 - see https://circleci.com/gh/tesch1/OpenVnmrJ/297

### CODE REVIEW

**Comment by DanIverson** [comment]
We should not need libxt-dev:i386 or libx11-dev:i386 either. We do need libx11-dev

**Comment by tesch1** [comment]
Ok, took those out, fails building Infostat now:

> gcc -o src/stat/Infostat -O2 -m32 -Wl,-rpath,/vnmr/lib src/stat/acqstat_win.o src/stat/statusscrn.o src/stat/statdispfuncs.o src/stat/statIPCfuncs.o src/stat/statsocket.o src/stat/acqinfo_xdr.o src/stat/shims.o -Lsrc/stat -Lsrc/ncomm -L/usr/lib32/i386-linux-gnu -L/usr/X11R6/lib -lXt -lX11 -lm -lacqcomm
> /usr/bin/ld: cannot find -lXt
> /usr/bin/ld: cannot find -lX11
> collect2: error: ld returned 1 exit status
> scons: *** [src/stat/Infostat] Error 1

**Comment by DanIverson** [comment]
My mistake. Looks like we still need them.

**Comment by DanIverson** [comment]
Can I select the commit you did on Aug 2 and not the one from Aug 5? The Aug 2 one is correct.

**Comment by tesch1** [comment]
Yes, definitely.  Would have done it myself, but temporarily separated from my desktop by an ocean.

**Comment by DanIverson** [comment]
Added PR #289, which is the first commit from this PR. My request for a second commit broke the stat category

**Pull request closed without merging**
