### PR TITLE
Make PI more accurate throughout the project

### PR DESCRIPTION
**Pull request by bdezonia**
Replaced 3.14, 3.1415, 3.1416, etc.

### CODE REVIEW

**Comment by bdezonia** [comment]
Closes #814

**Comment by bdezonia** [comment]
Dan, I have reviewed the conflicts and all the new code is correct. The old code was replaced on purpose. I do not have write access to the repo so I can't fix it.

**Comment by DanIverson** [comment]
I am ready to merge this. Could you make one final change. In src/vnmrbg/dli.c, DEG is defined twice. Could you remove the one on line 1289?

**Comment by bdezonia** [comment]
Dan, I am glad to but I can't find that file. Did you give me the right
path/file name?

**Comment by DanIverson** [comment]
Sorry. It is src/vnmr/dli.c

**Comment by bdezonia** [comment]
Found where you meant and have fixed it.

**Pull request merged**
