### PR TITLE
clear exec bit from text file permissions

### PR DESCRIPTION
**Pull request by tesch1**
.gitignore
*.[ch]
*.cpp
*.xml
*/procpar
*/text

### CODE REVIEW

**Comment by tesch1** [comment]
relevant build: https://circleci.com/gh/tesch1/OpenVnmrJ/176

**Comment by DanIverson** [comment]
I will do this PR but the file permissions in the dvd image should not rely on the file permissions in the git repo. The SConstructs that put files into the dvd image should make sure the file permission are correct.

**Comment by tesch1** [comment]
Ok, that makes sense.  I'll audit the dvd dirs.  It will probably be a couple weeks before I get to this - some other stuff has come up.

**Comment by DanIverson** [comment]
I think that most of the SConstructs already do the right thing with respect to permissions.

**Pull request merged**
