### PR TITLE
update vjqa build, test, and cleanup makeuser

### PR DESCRIPTION
**Pull request by tesch1**
- add circleci install & vjqa testing
- fix vjqa build when system java is not default/available
- added install_test.sh, a script to install and test
- added circleci failure logging hooks
- fix bug in makeuser.sh getting return value from make_homedir
- many shellcheck fixes to makeuser.sh
- use bash for circleci (not dash)
- moved shared shell log functions into loglib.sh
- added grok_warnings.py file to summarize logfiles

### CODE REVIEW

**Comment by tesch1** [comment]
https://circleci.com/gh/tesch1/OpenVnmrJ/148

**Comment by DanIverson** [comment]
A couple of observations about makeuser. If the user does not exist, the get_homedir() function fails. For example,

cur_homedir=$(get_homedir "try3")
returns ~try3
This then fails the test to make a home directory. The line
  echo "$(eval echo "~$1")" returns ~try3 while the older scheme
  csh -f 2>/dev/null << ++
echo ~$1
++
returns a null string.

Also, why are you adding .vnmrenvsh to the .bashrc file at line 702. The bash environment is already handled with the code dealing with .bash_profile and .profile at lines 862-874

I am still reviewing makeuser but I thought I would let you know what I found so far.

**Comment by DanIverson** [comment]
Oops. getent does not seem to be part of MacOS

**Comment by tesch1** [comment]
Eh, the .bashrc edit was because something else was failing silently and then I didn't understand why the environment never got set up, mistakenly assumed it was only setup for csh, and then when the other thing was fixed I didnt think to take it back out.

Came up with a bit of a dumber solution for get_homedir(), it's an extra line of code, but still removes the csh dependency.

**Comment by DanIverson** [comment]
One last question. In the previous makeuser, the debian commands usually required a sudo. The sudo was removed from the chmod on line 564.  Was that intended?

**Comment by tesch1** [comment]
Oops, dunno why I did that.

**Pull request merged**
