### PR TITLE
Development

### PR DESCRIPTION
**Pull request by DanIverson**
This should resolve issue #37

### CODE REVIEW

**Comment by timburrow** [comment]
Thanks for cleaning up the macOS linking. Quick q: why -O and not -Os? I think clang needs higher optimization numbers compared to gcc. -Os is the mac default.

**Comment by DanIverson** [comment]
I was hunting for reasons why the ios_base4Init error was occurring. The first thing I tried was changing the optimization. I guess I forgot to set it back after discovering it was not the problem.

**Comment by timburrow** [comment]
OK. I was worried there was an optimization bug lurking...

I got a build error, vnmr/craft is not found:
OSError: [Errno 2] No such file or directory: '/Volumes/Tim/Users/timburrow/Documents/OpenVnmrJ/github-timburrow/OpenVnmrJ/../vnmr/craft':
  File "/Volumes/Tim/Users/timburrow/Documents/OpenVnmrJ/github-timburrow/OpenVnmrJ/SConstruct", line 279:
    runSconsPostAction(os.path.join(vnmrPath, 'craft'))
  File "/Volumes/Tim/Users/timburrow/Documents/OpenVnmrJ/github-timburrow/OpenVnmrJ/SConstruct", line 270:
    dirList = os.listdir(dir)
scons returned: 2
===>>> scons Build error  <<<===

**Comment by DanIverson** [comment]
I am re-building now on my Mac. I will let you know if I get the same error.
For the Mac build, should pgsql.osx end up as /vnmr/pgsql? It is currently being copied to /vnmr/pgsql.osx

**Pull request merged**
