### PR TITLE
Fix more strncpy problems in the solidspack code

### PR DESCRIPTION
**Pull request by bdezonia**
There are numerous places in the soldispack code that make the same strncpy errors that we fixed with ah*.c files a day or two ago. I think this code needs to go in place soon. There were a number of places where strncpy(chan,"dec2",3) were present (with "dec2" getting chopped off and thus chan just being set to "dec"). Also there were hundreds of non-NULL terminated strings in the pulse sequences.

### CODE REVIEW

**Comment by DanIverson** [comment]
It looks like redor2tancp.c still has a problem. It is copying the strings "obs " and "dec ". That extra space should not be there.

**Comment by bdezonia** [comment]
I've fixed that now. Great catch! Thanks.

**Comment by bdezonia** [comment]
I'm not used to this process. This is the first repo I've ever made pull requests to. Now that I've made your fix do I need to open a new pull request? Or can you merge this updated branch instead?

**Comment by DanIverson** [comment]
Looks like it merged correctly.

**Pull request merged**
