### PR TITLE
Fix a likely bug in RFController.cpp

### PR DESCRIPTION
**Pull request by bdezonia**
This one might require discussion and testing. The existing code seems to have had a flaw due to poor code indentation.

### CODE REVIEW

**Comment by bdezonia** [comment]
BTW grepping for 0x28 in the OVJ turned up a number of lines related to this:

bluejay:~/dev/OpenVnmrJ/src> grep -r FIFOHighThreshold *
nvacq/pfg_reg.h:#define PFG_InstructionFIFOHighThreshold 0x28
nvacq/rf.h:#define RF_InstructionFIFOHighThreshold 0x28
nvacq/pfg.h:#define PFG_InstructionFIFOHighThreshold 0x28
nvacq/master.h:#define MASTER_InstructionFIFOHighThreshold 0x28
nvacq/ddr.h:#define DDR_InstructionFIFOHighThreshold 0x28
nvacq/gradient.h:#define GRADIENT_InstructionFIFOHighThreshold 0x28

All of them are .h defines and seemingly not referenced in C code so I can't find comments on what the code means but the names are a little suggestive. Maybe this is an entirely wrong path to investigate what the 0x28 means in the RFController.cpp code.

**Comment by bdezonia** [comment]
Maybe more hints?

bluejay:~/dev/OpenVnmrJ/src> grep -r 0x28 *
backproj/bp_3d.c:fhm.vers_id   = 0x2800;
backproj/bp_3d.c:fhi.vers_id   = 0x2800;
backproj/bp_2d.c:fhi.vers_id   = 0x2800;
bin/tfifo.c:  else if (reg_num >= 0x28 && reg_num <= 0x29)
bin/tfifo.c:    addrfcmd(strbuf,reg_num - 0x28,data);
bin/fifotrans.c:  else if (reg_num >= 0x28 && reg_num <= 0x29)
bin/fifotrans.c:    addrfcmd(outbuf,reg_num - 0x28);
bin/xltape.c:  *gg++ = 0x28; 
bootpd.rh51/hwaddr.c:	/* 0x10 */ 0x08, 0x88, 0x48, 0xC8, 0x28, 0xA8, 0x68, 0xE8,
bootpd.rh51/hwaddr.c:	/* 0x28 */ 0x14, 0x94, 0x54, 0xD4, 0x34, 0xB4, 0x74, 0xF4,
ib/crc.c:      0x2802b89e, 0x5f058808, 0xc60cd9b2, 0xb10be924,
kpsg/meat.c:       putcode(-APB_SELECT + RF_ADDR + 0x28);
kpsg/meat.c:       putcode(-APB_SELECT + RF_ADDR + 0x28);
kpsg/array.c:#define LPRIN 0x28	/* left  parenthesis */
kvwacq/AParser.c:	temp |= 0x28;
nvacq/pfg_reg.h:#define PFG_InstructionFIFOHighThreshold 0x28
nvacq/pfg_reg.h:#define PFG_instruction_fifo_high_threshold_addr 0x28
nvacq/md5.c:#define T1 /* 0xd76aa478 */ (T_MASK ^ 0x28955b87)
nvacq/md5.c:#define T41    0x289b7ec6
nvacq/shimHandlers.c:   setSPIbits(0,0x280);
nvacq/shimHandlers.c:        setSPIbits(0,0x280);
nvacq/shimHandlers.c:        setSPIbits(0,0x280);
nvacq/crc32.c:      0x2802b89e, 0x5f058808, 0xc60cd9b2, 0xb10be924,
nvacq/rf.h:#define RF_InstructionFIFOHighThreshold 0x28
nvacq/rf.h:#define RF_instruction_fifo_high_threshold_addr 0x28
nvacq/lock.h:#define LOCK_J1CInput 0x28
nvacq/lock.h:#define LOCK_J1_C_addr 0x28
nvacq/rfTests.c:/* other = 60 dBm  -> attn_out=-50, xmtr_out=-16   649 = 0x289 */
nvacq/pfg.h:#define PFG_InstructionFIFOHighThreshold 0x28
nvacq/pfg.h:#define PFG_instruction_fifo_high_threshold_addr 0x28
nvacq/master.h:#define MASTER_InstructionFIFOHighThreshold 0x28
nvacq/master.h:#define MASTER_instruction_fifo_high_threshold_addr 0x28
nvacq/ddr.h:#define DDR_InstructionFIFOHighThreshold 0x28
nvacq/ddr.h:#define DDR_instruction_fifo_high_threshold_addr 0x28
nvacq/gradient.h:#define GRADIENT_InstructionFIFOHighThreshold 0x28
nvacq/gradient.h:#define GRADIENT_instruction_fifo_high_threshold_addr 0x28
nvacq/icat_reg.h:#define iCAT_AverageTemperature 0x28
nvacq/icat_reg.h:#define iCAT_average_temperature_addr 0x28
nvpsg/RFController.cpp:  if (which > 3)  buffer[0] = 0x28;  // zero all
nvpsg/RFController.cpp:        0x39, 0x38, 0x59, 0x58, 0x19, 0x18, 0x69, 0x68, 0x29, 0x28,
nvpsg/arrayfuncs.c:#define LPRIN 0x28
psg/arrayfuncs.c:#define LPRIN 0x28
roboproc/crc16.c:    0x48c4,  0x58e5,  0x6886,  0x78a7,  0x0840,  0x1861,  0x2802,  0x3823,
roboproc/crc16.c:    0x5844,  0x4865,  0x7806,  0x6827,  0x18c0,  0x08e1,  0x3882,  0x28a3,
vnmr/go.c:#define LPRIN 0x28
vnmr/md5c.c:  HH (a, b, c, d, x[13], S31, 0x289b7ec6); /* 41 */
vnmr/data.h:#define S_OX		0x2800  /* 1 = Oxford data		*/ 
vnmrbg/smagic.c:#define LPRIN 0x28
vwauto/quart.c:    tyQCoDv [2].ipcr = (unsigned char *) SERIAL_QSC+0x28;
vwauto/quart.c:    tyQCoDv [2].acr = (unsigned char *) SERIAL_QSC+0x28;
vwauto/quart.c:    tyQCoDv [3].ipcr = (unsigned char *) SERIAL_QSC+0x28;
vwauto/quart.c:    tyQCoDv [3].acr = (unsigned char *) SERIAL_QSC+0x28;

**Comment by bdezonia** [comment]
Of course 0x28 hex equals 40 decimal. And the /src/nvpsg/acodes.h file has a code/instruction that == 40. This is what the definition looks like:

#define IFZFUNC    40   /* $28 050 test end of loop zero */

Again maybe I am poking around in the dark.

**Comment by DanIverson** [comment]
I agree the code looks strange but it has been tested and it works. These changes would alter the results for the (which > 3) case.

**Comment by DanIverson** [comment]
A change to make it clearer could be 

  int buffer[2];
  int mask, action;

  if (which > 3)  // zero all
  {  
     mask = 0;
     action = 0;
  }   
  else
  {
    mask = (1 << (which - 1));
    if (state)
       action = mask;
    else
       action = 0;
  }
  buffer[0] = (mask & 7) << 3 | (action & 7);
  outputACode(RFSPARELINE,1,buffer); // out they go..

However, I hesitate to make this change since changes at this level generally require substantial testing.

**Comment by bdezonia** [comment]
Yeah, I understand your reluctance. Your new code keeps the old behavior.
But the bug might be that we aren't sending the 0x28 (like we should have
all along) and rather we are always sending 0 in the which > 3 case.

**Comment by tesch1** [comment]
i think 0x28 [101,000] isnt even the right bit pattern to clear all - it should be 0x38 [111,000]  (unless the hardware only has lines 1 and 3 connected.)

**Comment by bdezonia** [comment]
Michael, I'm sure you meant this but just pointing out to Dan that It does
seem like if which > 3 then the mask is 7 << 3 (which equals 0x38) and
since it is a clear all action the action is 0. Combining the two together
in the fashion of the last line of the current method this
coincidentally just is 0x38. Right now we are sending mask = 0 and action =
0 when which > 3. I do think the current code is buggy.

**Comment by bdezonia** [comment]
Dan, I think more correct pseudocode would be:

int buffer[2];
int mask, action;

if (which > 3) // zero all
{
mask = 7;
action = 0;
}
else
{
mask = (1 << (which - 1));
if (state)
action = mask;
else
action = 0;
}
buffer[0] = (mask & 7) << 3 | (action & 7);
outputACode(RFSPARELINE,1,buffer); // out they go..


I know you're reluctant to address this but we should consider adopting it.
I don't know the difficulties with testing. As to whether it is working
well/right I think we do not know that. We know it is probably limping
along and maybe only occasionally presents some kind of problem.

**Pull request closed without merging**
