### PR TITLE
Development

### PR DESCRIPTION
**Pull request by timburrow**
All updates from August 27 to September 27

### CODE REVIEW

**Comment by DanIverson** [comment]
Okay, it looks like you merged development into master. I checked a few of
my changes and they are in master. The development branch still says it is
39 commits ahead of master and if you do a compare, it shows all the files
that were just merged into master from development. That just seems wrong.

**Comment by timburrow** [comment]
There seems to be something wrong with GitHub (or the repository branches). It took me 30 minutes to get the >> operator in place of the > operator. It was changed in all my forks, but never got merged into the OpenVnmrJ repository. I had to do the merge using the command line where it worked ok. 

Maybe delete development and make another branch?

**Comment by DanIverson** [comment]
Lets delete and remake development

**Comment by DanIverson** [comment]
I just checked master and development and the only difference is the
README.md file. The one in master looks newer so I will delete the
development branch

**Comment by DanIverson** [comment]
I have all my changes in OpenVnmrJ master branch. Are we ready to tag and
build a release?

**Comment by timburrow** [comment]
Yes. I'll start a build on CentOS. I'll replace to older OpenVnmrJ_1.1A tag and upload new compiled binaries. 

Michael: we have slack http://openvnmrj.slack.com/signup

**Comment by tesch1** [comment]
Yeah, github's doing some funky stuff.

---
it wants an @agilent.com email... otherwise...

"Don't have an @agilent.com email address?
Contact your Team Administrator for an invitation"

my email is tesch1@gmail.com  :o)

**Pull request merged**
