### PR TITLE
update package check for trusty 14.04

### LINKED ISSUE #23: Package ia32-libs required for install on Ubuntu (64-bit) but not available on Trusty or Xenial
Installation fails when installing on Ubuntu Trusty Tahr (64-bit) with a requirement for the package ia32-libs. No such package exists.  

I am not sure it is needed, multi arch allows one to specify the i386 version of libraries, and libc6 has a 32 bit version installed:  

```
apt list --installed | grep 386

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libc6-dev-i386/unknown,unknown,now 2.19-0ubuntu6.9 amd64 [installed]
libc6-i386/unknown,unknown,now 2.19-0ubuntu6.9 amd64 [installed,automatic]
libmotif-dev/unknown,now 2.3.4-5ubuntu0.1 i386 [installed]
```

Perhaps more 32-bit libraries are needed.

### PR DESCRIPTION
**Pull request by tesch1**
this fixes #23 and #22

### CODE REVIEW

**Comment by DanIverson** [comment]
Tim,
Are you planning to do this PR and re-make the OVJ 1.1A release and then tag it? If so, I have two minor fixes and 1 significant fix (qtune on Mercury does not work) to add. I can't add them until Monday.

**Comment by timburrow** [comment]
Hi Dan

I'll add your fixes and the openvnmr-utils directory to OpenVnmrJ Monday evening, tag and rebuild. I added Michael's PR already (he added an Apache license header)

Cheers
Tim

**Comment by tesch1** [comment]
i'm not sure why there's 5 commits on this, I think it'be because I started with the master branch.  hopefully squashing this into a single commit when doing the merge will get rid of them.

**Comment by DanIverson** [comment]
I am still a little confused by this process. I just finished pulling my changes from the development branch of DanIverson/OpenVnmrJ into the development branch of OpenVnmrJ/OpenVnmrJ. If I select the development branch, it says something like 22 commits ahead and 6 commits behind master. I have not yet made a PR from development to master. If I do a compare, most of the commits have already been pulled into master. I don't know why they are still showing up in development

**Comment by tesch1** [comment]
Github just added a "rebase and merge" option to the "Merge pull request" button on pull requests, which I think would do the right thing for this situation.

**Comment by timburrow** [comment]
I did the new "rebase and merge" on this PR

**Comment by tesch1** [comment]
Hm, well it seems to have only brought over the two commits from me, so that's good.  In retrospect though, probably should have squashed them together.

**Comment by timburrow** [comment]
I'll add some of my changes into this dev branch, then merge the development branch with master.
Squash & Merge? (what I'd usually do)
Rebase and Merge?
Just Merge and keep the history?

**Comment by tesch1** [comment]
For this one, it doesn't matter.
For the future, to clarify, every PR that goes into development gets squashed, and every PR to master gets rebased and merged (or just merged?) :  So every commit on development is a functional group of changes, and master gets merged with collections of commits that have been tested together?

**Pull request merged**
