### PR TITLE
Added compiled console code

### PR DESCRIPTION
**Pull request by DanIverson**
This PR includes changes to add compiled console code to the
dvd images. The console code is in ovjTools/console. The ovjTools
PR number 36 is required.

### CODE REVIEW

**Comment by tesch1** [comment]
what about putting the variable into the buildoptions.py file, like: 
https://github.com/DanIverson/OpenVnmrJ/compare/console...tesch1:console-bo?expand=1

to keep the build config in one place.

**Comment by DanIverson** [comment]
I was slowly trying to get rid of buildoptions.py, but if you think it makes more sense to set the option there, that works for me.

When buildovj is executed, the makeovj script copies the ovjddrout.sh and ovjmiout.sh to the local directory and then runs make on them. This creates the files without the .sh extension and sets the x bit. I am not sure what needs to be done in build_release.

**Comment by tesch1** [comment]
build_release just needs the r,x bits to be set on those files, doesn't need to copy them anywhere.

I think buildoptions.py seems like an ok place to keep all the build options that affect scons' stuff together, it's a little kludgey the way it is now, but at least they're all in one place using the same idiom.

(imho) ideally everythign could be built and configured with scons alone (no shell scripts), but I think more comprehensive automated testing is needed before revamping the whole build.

**Comment by tesch1** [comment]
here's a rough idea for buildoptions.py ... it pulls all the config into bo.py so all SConscripts get the same config, and uses scons' command-line parsing to parse options from the command-line and a `config.py` (which used to be buildoptions.py at the top level).   https://github.com/OpenVnmrJ/OpenVnmrJ/compare/master...tesch1:mt-scons-options?expand=1

**Pull request merged**
