### PR TITLE
Init all instance member variables to 0 in LockController

### PR DESCRIPTION
**Pull request by bdezonia**

### CODE REVIEW

**Comment by bdezonia** [comment]
Dan, I am just noticing a possible bug in this routine:

https://github.com/OpenVnmrJ/OpenVnmrJ/blob/a22a110ec33363af8256243a3d3b18ed2a2b7220/src/nvpsg/LockController.cpp#L96

Notice that setLockFreq() actually (and I think accidentally) sets lockGain. There already is a setLockGain() method.

**Comment by bdezonia** [comment]
I have verified that setLockOffsetFrequency() is not called from anywhere within the source. To be safe we should fix this code.

**Comment by bdezonia** [comment]
I should be clear. setLockOffsetFrequiency() does send outputACode() the right thing. But the routine sets the lockGain instance variable rather than the lockOffsetFreq instance variable.

**Comment by DanIverson** [comment]
I think the four private lock attributes in LockController.h and all of the methods the "set" and "get" them in LockControllers.cpp are all dead code.

**Pull request merged**
