### PR TITLE
Fix bashloc & update gold-circleci

### PR DESCRIPTION
**Pull request by tesch1**
I've been playing with {free}bsd portability, should be pretty similar to osx since Apple borrowed a bunch of the unix environment from freebsd.  One big difference is that bash isn't installed in /usr.

The cleanup of vjqa warnings is great.

### CODE REVIEW

**Comment by tesch1** [comment]
https://circleci.com/gh/tesch1/OpenVnmrJ/274

**Comment by DanIverson** [comment]
It is easy to remove the dependence on libnsl, which I will do. The rpc stuff is used by obsolete features. Rather then implement these with tirpc, we could just remove them. That will take a little more time since it involves three or four programs.

**Comment by tesch1** [comment]
I think the javac/jar in ovjTools also needed libnsl (`ldd` doesn't show it, iirc it's loaded dynamically)

**Comment by DanIverson** [comment]
Yes, you are correct. The java categories fail. I cheated and did
  cd /usr/lib64
  sudo ln -s libnsl.so.2.0.0 libnsl.so.1
All of the java compiles then work. After removing infoproc, nvinfoproc, and stat from the build list, for the rpc issue, everything compiled

**Comment by DanIverson** [comment]
I am a bit concerned about the tirpc stuff. If we build with that library, then if an existing user tries to install OVJ on a CentOS 6 or 7 system, the Infoproc and stat stuff will fail. I am also not comfortable making these changes without an actual system to test it on. Even removing the rpc stuff from these programs is tricky enough that I would want to test the changes on a real system.

Would it be possible for the stat, infoproc, and nvinfoproc SConstruct files to check to see if the /usr/include/rpc include files are present. If so, build with the old rpc scheme. If not, then if the tirpc library or /usr/include/tipcr is present, use that. If neither are present, just skip the build. 

For other files in this PR,
  the 3D/SConstruct can be removed since only comment lines are added.
  can you remove scripts/ins_vnmr2.sh from your PR. I have made a number of other changes and am about ready to push them. I have incorporated the changes from your PR.
  can you remove scripts/ovjGetpipe.sh from your PR. There are some other bugs I am in the process of fixing and will include your change in my update.

I have not finished testing this new stuff yet, but hope to get to it soon.

**Comment by tesch1** [comment]
yep, I'll make these changes in the next few days.

**Comment by tesch1** [comment]
few := (x > 3)
still working on it...

**Comment by tesch1** [comment]
Ok, I'm going to move the [ti]rpc stuff to a separate PR.  What's left here:

- some script cleanups that reduce reliance on certain bash/linux features
- bash shebang

On the second, I'm having second thoughts on the "shebang uses /usr/bin/env" to find bash question, and keep going back and forth as to which side I'm on.  It was initially because bash is installed at /usr/bin/bash on freebsd, but really that's the only platform, and freebsd is a novelty project at this point (an exercise in portability), and in that special case can just be symlinked to /bin/bash.  It's not so unreasonable to assume/require that bash is /bin/bash.  It also subjects all the scripts to any weird stuff people might have in their paths.  OTOH, Apple is sticking to bash 3 in /bin/bash because bash4 changed to GPL3, so at some point we may want to use a newer bash on macos... in some theoretical future, hrm.  Thoughts?

As to whether user accounts we create have the shell set, what if the created user's login shell just isnt' set explicitly?  (via adduser's `--shell`).

Shell commands that are run from within programs using `system()` always use `/bin/sh` (which is only sometimes bash, as we've see on ubuntu) and any processing scripts that launch shells shouldn't be creating login shells based on whatever's configured in /etc/passwd (right...? I guess this is an unverified assumption but seams reasonable).  But then there's the principle of "changing a working system" and causing possible unknown issues.

**Comment by tesch1** [comment]
ps. regarding your request above.. I dont see changes in 3D/SConstruct or scripts/ovjGetpipe.sh

**Comment by DanIverson** [comment]
My PR  #265 has your changes to makeuser.sh so it can be removed from this PR. I did not make changes to 3D/SConstruct. Your changes were only comments and I see that you removed it from this PR. My changes to scripts/ovjGetpipe.sh are in PR #262 .

I read some comments about #!/usr/bin/env bash vs. #!/bin/bash. There is definitely no consensus. The "env" side likes portability and flexibility. The /bin/bash side questions the portability. The /bin/bash side likes the deterministic aspect. I also think /bin/bash comes out a little ahead on performance. On average, I guess I come down on the side of /bin/bash, but not enough to make me change the ones already switched to #!/usr/bin/env bash. MacOS and bash4 probably tilt toward the "env" side.

I am not sure what happens if shell is not set in passwd. I was thinking of always setting it to bash instead of csh, which we use now. My hesitation is that NMRPipe requires csh and I am not sure if the change to bash would cause problems.

**Comment by tesch1** [comment]
finally had a minute to clean this up... sorry for the huge delay..

I've squashed it all down to one commit and limited it to the script portability issues and the circleci gold update - full details in the commit message.

I think /bin/bash is better for now, until there's really a need to change.  Interestingly, fedora30 (and presumably RHEL8.. havent seen it yet though) has moved the default login shell bash to /usr/bin/bash, but still has a hard link at /bin/bash.  Could be an omen of things to come, but there are so many linux scripts with hard-coded /bin/bash out in the wild it's unlikely to go away in the near-term.

Here's the build - assuming it goes ok, I think this patch is ready..
https://circleci.com/gh/tesch1/OpenVnmrJ/293

**Pull request merged**
